#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 28 08:34:55 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=ComplementaryUnbound_r5.8.zip
